name: Validate Gradle Wrapper
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  validation:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3.5.0
